<?php

const TASTE = [
    'sweetness' => 'сладость',
    'saltiness' => 'соленость',
    'sourness' => 'кислинка',
    'bitterness' => 'горчинка',
    'savoriness' => 'пикантность',
    'fattiness' => 'жирность',
    'spiciness' => 'острота',
];

const NUTRIENTS = [
    "Potassium" => "Калий",
    "Vitamin E" => "Витамин Е",
    "Protein" => "Протеин",
    "Phosphorus" => "Фосфор",
    "Vitamin B3" => "Витамин В3",
    "Fluoride" => "Фторид",
    "Fiber" => "Пищевые волокна",
    "Poly Unsaturated Fat" => "Полиненасыщенные жиры",
    "Vitamin B5" => "Витамин В5",
    "Vitamin D" => "Витамин D",
    "Calcium" => "Кальций",
    "Caffeine" => "Кофеин",
    "Sugar" => "Сахар",
    "Mono Unsaturated Fat" => "Мононенасыщенные жиры",
    "Calories" => "Калории",
    "Vitamin A" => "Витамин A",
    "Vitamin C" => "Витамин C",
    "Saturated Fat" => "Насыщенные жиры",
    "Trans Fat" => "Трансжиры",
    "Iron" => "Железо",
    "Vitamin B12" => "Витамин В12",
    "Vitamin B1" => "Витамин В1",
    "Cholesterol" => "Холестерин",
    "Alcohol" => "Алкоголь",
    "Net Carbohydrates" => "Чистые углеводы",
    "Vitamin B6" => "Витамин В6",
    "Carbohydrates" => "Углеводы",
    "Manganese" => "Марганец",
    "Fat" => "Жиры",
    "Vitamin B2" => "Витамин В2",
    "Folate" => "Фолат",
    "Magnesium" => "Магний",
    "Copper" => "Медь",
    "Vitamin K" => "Витамин К",
    "Sodium" => "Натрий",
    "Zinc" => "Цинк",
    "Selenium" => "Селен"
];

const MEASURES = [
    'g' => 'гр',
    'tbsp' => 'ст. ложка',
    'tbsps' => 'ст. ложки',
    'cups' => 'чашки',
    'cup' => 'чашка',
    'cloves' => 'дольки',
    'ounces' => 'унции',
    'pinches' => 'щепотки',
    'servings' => 'порции',
    'mg' => 'мг',
    'container' => 'упаковка',
    'kcal' => 'ккал',
    'µg' => 'µg',
    'IU' => 'IU',
];
